# Generated by Django 3.1.6 on 2021-04-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
